# -*- coding: utf-8 -*-
"""halo_dunia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19o8Rb15abyAHA-L05AKC93HK3JzTIMIK
"""

print('Halo Dunia !')